#pragma once
#include "AssetModel.h"
#include "AssetDerivative.h"
#include "DerivativeDataClass.h"
#include <vector>
#include <map>
#include <deque>

#ifdef CUSTOM_DERIVATIVE_PRICING_API_EXPORTS
#define CUSTOM_DERIVATIVE_PRICING_API __declspec(dllexport)
#else
#define CUSTOM_DERIVATIVE_PRICING_API __declspec(dllimport)
#endif

class CUSTOM_DERIVATIVE_PRICING_API DerivativeSimulator
{
public:
	DerivativeSimulator(AssetModel model);

	DerivativeSimulator(const DerivativeSimulator&) = delete;
	DerivativeSimulator& operator=(const DerivativeSimulator&) = delete;

	/// @brief Simulates possible paths for the asset price based on the asset price model. Utilizes multiple threads.
	/// @param numThreads The number of threads used to simulate prices.
	/// @param numSimulations The number of price simulations per thread.
	/// @param numDays The number of days prices are simulated for.
	void runSimulations(int numThreads, int numSimulations, int numDays);

	/// @brief Adds a particular derivative to the derivatives simulated.
	/// @param derivative A unique pointer to an AssetDerivative object.
	void addDerivative(std::unique_ptr<AssetDerivative> derivative);

	bool hasAssetData(int simIndex, int day, AssetDataClass dataClass) const;
	std::any getAssetData(int simIndex, int day, AssetDataClass dataClass) const;

private:
	const AssetModel model;  // The initial model of each simulation.
	std::vector<std::unique_ptr<AssetDerivative>> derivatives;

	std::deque<std::map<int, std::map<AssetDataClass, std::any>>> assetData;  // [Sim Index][Day][Data Class] // Asset data generated by simulations.
	std::deque<std::map<int, std::map<DerivativeDataClass, double>>> derivativeData;  // [Sim Index][Day][Data Class]

	/// @brief Simulates asset price using model and determines derivative values.
	/// @param threadNum The number of price simulations per thread.
	/// @param numSimulations The number of price simulations per thread.
	/// @param numDays The number of days per simulation.
	void simulate(int threadNum, int numSimulations, int numDays);
};

extern "C"
{
	CUSTOM_DERIVATIVE_PRICING_API DerivativeSimulator* DerivativeSimulator_new(AssetModel* model, AssetDerivative* derivative);
	CUSTOM_DERIVATIVE_PRICING_API void DerivativeSimulator_delete(DerivativeSimulator* obj);
	CUSTOM_DERIVATIVE_PRICING_API void DerivativeSimulator_runAssetSimulations(DerivativeSimulator* obj, int numThreads, int numSimulations, int numDays);
	CUSTOM_DERIVATIVE_PRICING_API bool DerivativeSimulator_hasAssetData(DerivativeSimulator* obj, int simIndex, int day, int assetDataClass);
	CUSTOM_DERIVATIVE_PRICING_API int DerivativeSimulator_getIntAssetData(DerivativeSimulator* obj, int simIndex, int day, int assetDataClass);

}

